/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request {
	int x;
	int y;
	int ans;
	int choice;
};
typedef struct request request;

struct response {
	int value;
	int code;
};
typedef struct response response;

#define calc_prg 0x32345676
#define calc_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define calc 1
extern  response * calc_1(request *, CLIENT *);
extern  response * calc_1_svc(request *, struct svc_req *);
extern int calc_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calc 1
extern  response * calc_1();
extern  response * calc_1_svc();
extern int calc_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_request ();
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
